# AUTO-GENERATED by emit-stage-sdk — do not edit.
# Run: just gen-stage-sdk
#
# The BranchKit pipeline event vocabulary, projected from
# contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
# types). Framing lives in the hand-written reader/writer alongside this file.
#
# The audio session vocabulary. Import this if your stage produces or
# consumes an audio stream.

from typing import Any, NotRequired, TypedDict

# Wire event tags. Use these instead of string literals so vocabulary
# drift is a name error rather than a silent no-op.
EVENT_AUDIO_CHUNK = "audio_chunk"
EVENT_AUDIO_START = "audio_start"
EVENT_AUDIO_STOP = "audio_stop"

AudioChunk = TypedDict("AudioChunk", {
    "session_id": str,
    "timestamp_ms": int,
})

AudioFormat = TypedDict("AudioFormat", {
    "channels": int,
    "rate": int,
    "width": int,
})

AudioStart = TypedDict("AudioStart", {
    "format": "AudioFormat",
    "session_id": str,
})

AudioStop = TypedDict("AudioStop", {
    # Shared-clock position (the AudioChunk `timestamp_ms` timebase) after
    # which buffered audio must NOT be processed. Set when the stop was
    # triggered by something whose audio position is known — a recognized
    # stop phrase, say — so that a consumer buffering ahead of the trigger
    # does not process audio the user never meant to send.
    #
    # A source stage forwards it verbatim on its downstream AudioStop; a
    # batch consumer truncates its buffer at it; absent = process
    # everything.
    "cutoff_ms": NotRequired[int],
    "session_id": str,
})

