# AUTO-GENERATED by emit-sdk — do not edit.
# Run: just contracts

from typing import NotRequired, TypedDict

# INPUT_DIRECTIVE_* are the closed-vocabulary keys plugins may write
# into `_platform.input.directives`. Source of truth:
# `actuator/src/state.rs::InputDirectives::KNOWN_KEYS`.
INPUT_DIRECTIVE_LIFT_KEYS_ON_DISPATCH = "lift_keys_on_dispatch"

# EFFECT_* are the registered effect names plugins may declare in
# `consumes.effects`. Source of truth:
# `actuator/src/effects.rs::EffectDef` inventory entries.
EFFECT_DISABLE_SCREEN_DIM = "disable_screen_dim"
EFFECT_PREVENT_SYSTEM_SLEEP = "prevent_system_sleep"
EFFECT_SIGNAL_CLIPBOARD_IN_USE = "signal_clipboard_in_use"
EFFECT_SIGNAL_RECORDING_ACTIVE = "signal_recording_active"
EFFECT_SUPPRESS_HUDS = "suppress_huds"
EFFECT_SUPPRESS_KEYBINDS = "suppress_keybinds"
EFFECT_SUPPRESS_NOTIFICATIONS = "suppress_notifications"
EFFECT_SUPPRESS_VOICE_COMMANDS = "suppress_voice_commands"

# The full closed-vocabulary sets.
KNOWN_INPUT_DIRECTIVES = (
    "lift_keys_on_dispatch",
)

KNOWN_EFFECTS = (
    "disable_screen_dim",
    "prevent_system_sleep",
    "signal_clipboard_in_use",
    "signal_recording_active",
    "suppress_huds",
    "suppress_keybinds",
    "suppress_notifications",
    "suppress_voice_commands",
)

# ERROR_KIND_* are the closed-vocabulary `kind` values the actuator puts
# in a JSON-RPC error's `data.kind`. Branch on RpcCallError.kind rather
# than matching the message prose. Source of truth:
# `actuator/src/fault.rs::ErrorKind`.
#
# NOTE: ErrorKind is `str`, deliberately NOT a Literal union of the
# values below. An actuator newer than this SDK may send a kind that is
# not listed here, and that must fall through a match rather than fail
# to parse.
ErrorKind = str
ERROR_KIND_NOT_PERMITTED = "not_permitted"
ERROR_KIND_RECORDING_DISABLED = "recording_disabled"
ERROR_KIND_NOT_FOUND = "not_found"
ERROR_KIND_VALIDATION = "validation"
ERROR_KIND_FORBIDDEN = "forbidden"
ERROR_KIND_STORAGE = "storage"
ERROR_KIND_METHOD_NOT_FOUND = "method_not_found"
ERROR_KIND_INVALID_PARAMS = "invalid_params"
ERROR_KIND_INTERNAL = "internal"

# ERROR_CODE_FOR maps a kind to the JSON-RPC error code the actuator
# sends with it. Derived from the kind actuator-side.
ERROR_CODE_FOR: dict[str, int] = {
    "not_permitted": -32002,
    "recording_disabled": -32006,
    "not_found": -32001,
    "validation": -32004,
    "forbidden": -32003,
    "storage": -32005,
    "method_not_found": -32601,
    "invalid_params": -32602,
    "internal": -32603,
}

# KNOWN_ERROR_KINDS lists the full closed-vocabulary set.
KNOWN_ERROR_KINDS = (
    "not_permitted",
    "recording_disabled",
    "not_found",
    "validation",
    "forbidden",
    "storage",
    "method_not_found",
    "invalid_params",
    "internal",
)

# FaultData is the structured payload of a JSON-RPC error's `data`
# member. Only `kind` is guaranteed; the rest are populated when they
# apply. Source of truth: `actuator/src/fault.rs::FaultData`.
FaultData = TypedDict("FaultData", {
    "kind": str,
    "collection": NotRequired[str],
    "detail": NotRequired[str],
    "id": NotRequired[str],
    "op": NotRequired[str],
})
