# AUTO-GENERATED by emit-stage-sdk — do not edit.
# Run: just gen-stage-sdk
#
# The BranchKit pipeline event vocabulary, projected from
# contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
# types). Framing lives in the hand-written reader/writer alongside this file.
#
# Transport vocabulary: the handshake, framing, error and flow-credit
# types every stage speaks whatever its domain.

from typing import Any, NotRequired, TypedDict
from .audio.events_gen import AudioFormat

# Wire event tags. Use these instead of string literals so vocabulary
# drift is a name error rather than a silent no-op.
EVENT_CAPABILITY = "capability"
EVENT_ERROR = "error"
EVENT_FLOW_CREDIT = "flow_credit"

# The open namespace a stage emits custom events under: at least three
# non-empty dot segments, `ext.<vendor>.<name>`.
#
# This is the namespace EVERY domain the platform does not itself decode
# lives in — a foot pedal, a frame source, a MIDI filter. It needs no
# platform change and no entry in any catalog.
EXT_EVENT_PREFIX = "ext."


def is_valid_ext_event_type(t: str) -> bool:
    """Is this custom event type well-formed?"""
    if not t.startswith(EXT_EVENT_PREFIX):
        return False
    parts = t.split(".")
    return len(parts) >= 3 and all(parts)


# Environment variables the platform sets when it spawns a stage.
# NEVER re-derive these paths: the sandbox grants access by the path the
# platform computed, so a second spelling is a denial that reads like a
# missing directory.
MODELS_DIR_ENV = "BRANCHKIT_MODELS_DIR"
DATA_DIR_ENV = "BRANCHKIT_STAGE_DATA"

Capability = TypedDict("Capability", {
    # Custom event types this stage accepts as CONFIGURATION from the plugin
    # that ships it — exact `ext.<vendor>.<name>` types, or `ext.<vendor>.*`
    # globs.
    #
    # Distinct from [`Capability::consumes`], and deliberately not folded
    # into it. `consumes` is the stage-to-stage valve: its types arrive from
    # the stage ABOVE in the pipeline, and the wiring check fails loudly when
    # the upstream neighbour does not emit a declared type. Plugin config has
    # no upstream neighbour, so reusing `consumes` would make every stage
    # that wants config fail to wire. Two different relations, two fields.
    #
    # The direction this opens is plugin → a stage it ships. It does not
    # loosen the bus rule: plugin emits of `ext.*` ONTO THE EVENT BUS stay
    # rejected, because a bus subscriber trusts the source attribution. A
    # message sent here never reaches the bus — it is written to one stage's
    # stdin, the recipient is named by the sender, and the platform checks
    # that the sender ships that stage. There is no attribution to forge.
    #
    # A stage should apply config it receives and keep working without it.
    # Gate on config only when the stage cannot be CORRECT without it (an
    # unseeded recognition grammar decodes to garbage, so `sherpa_commands`
    # drops audio until seeded); config that only improves QUALITY — a
    # decoder bias list, say — must never block the stage's real work.
    #
    # Empty = the stage accepts no plugin configuration, which is every
    # pre-existing stage.
    "accepts_config": NotRequired[list[str]],
    "audio_formats": NotRequired[list["AudioFormat"]],
    # Custom event types this stage accepts from the stage ABOVE it in a
    # pipeline — exact `ext.<vendor>.<name>` types, or `ext.<vendor>.*`
    # globs.
    #
    # This is the stage-to-stage valve. The typed families (`audio_*`,
    # `transcript`) always flow to the next stage and need no declaration;
    # `ext.*` events do not, because the platform's default for a vocabulary
    # it cannot decode is to hop it onto the event bus. Declaring a type here
    # says "send it to me instead", which is what lets two stages agree on a
    # vocabulary the platform knows nothing about — frames, MIDI, sensor
    # readings, anything.
    #
    # Checked when the pipeline is wired: a declared type its upstream
    # neighbour does not emit is a mis-wire and fails loudly, rather than
    # leaving the stage waiting for something that can never arrive.
    #
    # Forwarded events are NOT also published to the bus — downstream
    # delivery replaces it. Backpressure on them is the pipe's, not the
    # credit window's: a flooding producer blocks on the OS buffer. The
    # windowed credit that `audio_chunk` gets buys abort and visibility on
    # top of that, and no custom vocabulary has needed it yet.
    "consumes": NotRequired[list[str]],
    # Event types this stage emits — built-in tags (`transcript`,
    # `power_snapshot`, …) and/or custom types under [`EXT_EVENT_PREFIX`]
    # (an `ext.<vendor>.*` glob covers a vendor namespace). Advisory at
    # runtime (the platform logs undeclared `ext.*` emissions rather than
    # dropping them); enforced by the conformance harness. Empty = the
    # stage declares nothing (pre-existing stages).
    "emits": NotRequired[list[str]],
    "feature_flags": NotRequired[dict[str, Any]],
    "lifecycle_modes": list[str],
    "stage_name": str,
    "stage_type": str,
})

ErrorEvent = TypedDict("ErrorEvent", {
    "code": str,
    "fatal": bool,
    "message": str,
    "session_id": NotRequired[str],
})

FlowCredit = TypedDict("FlowCredit", {
    "frames": int,
    "session_id": str,
})

# The serialized header line — one JSON object per event, newline-terminated,
# followed by exactly `payload_length` raw bytes when non-zero. `data` is
# omitted when empty/null; `payload_length` is omitted when zero.
WireHeader = TypedDict("WireHeader", {
    "data": NotRequired[Any],
    "payload_length": NotRequired[int],
    "type": str,
})

