# AUTO-GENERATED by emit-stage-sdk — do not edit.
# Run: just gen-stage-sdk
#
# The BranchKit pipeline event vocabulary, projected from
# contracts/pipeline.json (itself generated from the branchkit-stage-sdk Rust
# types). Framing lives in the hand-written reader/writer alongside this file.
#
# First-party monitor families. Typed because the platform renames them
# onto its bus as `_platform.*` events; a third-party monitor uses
# `ext.<vendor>.*` instead and needs nothing from here.

from typing import Any, NotRequired, TypedDict

# Wire event tags. Use these instead of string literals so vocabulary
# drift is a name error rather than a silent no-op.
EVENT_AUDIO_DEVICE_ADDED = "audio_device_added"
EVENT_AUDIO_DEVICE_DEFAULT_CHANGED = "audio_device_default_changed"
EVENT_AUDIO_DEVICE_REMOVED = "audio_device_removed"
EVENT_AUDIO_DEVICE_SNAPSHOT = "audio_device_snapshot"
EVENT_DISPLAY_ADDED = "display_added"
EVENT_DISPLAY_CHANGED = "display_changed"
EVENT_DISPLAY_REMOVED = "display_removed"
EVENT_DISPLAY_SNAPSHOT = "display_snapshot"
EVENT_HEADING_UPDATE = "heading_update"
EVENT_LOCATION_ERROR = "location_error"
EVENT_LOCATION_UPDATE = "location_update"
EVENT_POWER_SNAPSHOT = "power_snapshot"
EVENT_POWER_SOURCE_CHANGED = "power_source_changed"

AudioDeviceAdded = TypedDict("AudioDeviceAdded", {
    "device": "AudioDeviceInfo",
})

AudioDeviceDefaultChanged = TypedDict("AudioDeviceDefaultChanged", {
    "device_id": int,
    "direction": str,
    "name": str,
    "uid": str,
})

AudioDeviceInfo = TypedDict("AudioDeviceInfo", {
    "device_id": int,
    "is_default_input": bool,
    "is_default_output": bool,
    "is_input": bool,
    "is_output": bool,
    "name": str,
    "uid": str,
})

AudioDeviceRemoved = TypedDict("AudioDeviceRemoved", {
    "device_id": int,
    "name": str,
    "uid": str,
})

AudioDeviceSnapshot = TypedDict("AudioDeviceSnapshot", {
    "devices": list["AudioDeviceInfo"],
})

DisplayAdded = TypedDict("DisplayAdded", {
    "display": "DisplayInfo",
})

DisplayChanged = TypedDict("DisplayChanged", {
    "display": "DisplayInfo",
})

DisplayInfo = TypedDict("DisplayInfo", {
    "display_id": int,
    "height": int,
    "is_builtin": bool,
    "is_main": bool,
    "refresh_rate": float,
    "scale_factor": float,
    "width": int,
})

DisplayRemoved = TypedDict("DisplayRemoved", {
    "display_id": int,
})

DisplaySnapshot = TypedDict("DisplaySnapshot", {
    "displays": list["DisplayInfo"],
})

HeadingUpdate = TypedDict("HeadingUpdate", {
    "heading_accuracy": float,
    "magnetic_heading": float,
    "timestamp": float,
    "true_heading": float,
})

LocationError = TypedDict("LocationError", {
    "code": str,
    "message": str,
})

LocationUpdate = TypedDict("LocationUpdate", {
    "altitude": float,
    "horizontal_accuracy": float,
    "latitude": float,
    "longitude": float,
    "timestamp": float,
    "vertical_accuracy": float,
})

PowerSnapshot = TypedDict("PowerSnapshot", {
    "state": "PowerState",
})

PowerSourceChanged = TypedDict("PowerSourceChanged", {
    "state": "PowerState",
})

PowerState = TypedDict("PowerState", {
    "battery_level": NotRequired[float],
    "is_charging": bool,
    "source": str,
    "time_to_empty": NotRequired[int],
    "time_to_full": NotRequired[int],
})

